os: Visual Studio 2015

# Test with the latest two releases of MSVC
configuration:
  - 2015

# Test with the latest Lua and LuaJIT versions
platform:
  - x86
  - x86_amd64

matrix:
  fast_finish: true

install:
  - git submodule update --init
  - mkdir build

build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%
  - call build.bat LuaJIT
  - call build.bat lua

artifacts:
  - path: build\lua51.dll
  - path: build\luajit.exe
  - path: build\lua53.dll
  - path: build\lua53.exe  
